version: "3.1"
services:
  app:
    image: app/backend
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mongo:latest
    restart: always
    container_name: "database-container"
    ports:
      - 27017:27017
