version: "3"
services:
  app:
    image: app/backend
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    container_name: "database-container"
    ports:
      - 27017:27017
